version: "3.9"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: guestbook-db
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - guestbook_net

  # Backend API
  api:
    build: ./backend
    image: backend
    container_name: guestbook-api
    environment:
      - MONGO_URL=mongodb://mongodb:27017/guestbook
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - guestbook_net

  # Frontend â€“ static HTML with nginx
  web:
    image: nginx:alpine
    container_name: guestbook-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - guestbook_net

networks:
  guestbook_net:

volumes:
  mongo_data: